name: Moby Compile

on:
  # Allow to trigger action manually
  workflow_dispatch:

jobs:
  check_version:
    runs-on: self-hosted

    steps:
    - name: Install dependencies
      run: sudo apt-get -y install git make pkg-config libdevmapper-dev libseccomp-dev libbtrfs-dev jq gcc xz-utils

    - name: Check versions
      run: |
        # Set Golang path
        PATH=$PATH:/opt/golang/bin

        # Get Docker version and create necessary directories
        DOCKERD_V=$(curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} -s https://api.github.com/repos/moby/moby/releases/latest | jq -r '.tag_name')
        BUILDDIR=${{ github.workspace }}/$DOCKERD_V
        PACKAGEDIR=$BUILDDIR/docker
        mkdir -p $PACKAGEDIR/usr/sbin $PACKAGEDIR/usr/bin/docker $PACKAGEDIR/DEBIAN
        
        # dockerd
        cd $BUILDDIR
        git clone --branch $DOCKERD_V --single-branch --depth 1 https://github.com/moby/moby.git
        cd $BUILDDIR/moby
        export DOCKER_BUILDTAGS="exclude_graphdriver_devicemapper exclude_graphdriver_aufs nosystemd"
        ./hack/make.sh binary

        cp $BUILDDIR/moby/bundles/binary-daemon/dockerd $PACKAGEDIR/usr/sbin/dockerd
        cp $BUILDDIR/moby/bundles/binary-daemon/docker-proxy $PACKAGEDIR/usr/sbin/docker-proxy

        # docker-cli
        cd $BUILDDIR
        export GOPATH=${{ github.workspace }}/go
        export DISABLE_WARN_OUTSIDE_CONTAINER=1
        git clone --branch $DOCKERD_V --single-branch --depth 1 https://github.com/docker/cli
        mkdir -p ${{ github.workspace }}/go/src/github.com/docker/cli
        cp -R $BUILDDIR/cli/* ${{ github.workspace }}/go/src/github.com/docker/cli
        cd $BUILDDIR/cli
        make binary -j20
        cp $BUILDDIR/cli/build/docker-linux-amd64 $PACKAGEDIR/usr/bin/docker

        cat > $PACKAGEDIR/DEBIAN/control << EOF
        Package: Docker
        Version: ${DOCKERD_V#v}
        Architecture: amd64
        Maintainer: admin@minenet.at
        Description: Custom Docker build for MOS
        EOF

        cd $BUILDDIR
        dpkg-deb --build docker

        echo "DOCKERD_V=$DOCKERD_V" >> $GITHUB_ENV

        #rm -rf ${{ github.workspace }}
