name: Docker Compile

on:
  # Allow to trigger action manually
  workflow_dispatch:

jobs:
  build_docker:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: apt-get update && apt-get -y install git make pkg-config libdevmapper-dev libseccomp-dev libbtrfs-dev jq gcc xz-utils

    - name: Compile Docker
      run: |
        # Set Golang path
        PATH=$PATH:/opt/golang/bin

        # Get Docker version and create necessary directories
        DOCKERD_V=$(curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} -s https://api.github.com/repos/moby/moby/releases/latest | jq -r '.tag_name')
        BUILDDIR=${{ github.workspace }}/$DOCKERD_V
        PACKAGEDIR=$BUILDDIR/docker_package
        mkdir -p $PACKAGEDIR/usr/sbin $PACKAGEDIR/usr/bin $PACKAGEDIR/usr/lib/docker/cli-plugins $PACKAGEDIR/etc/init.d $PACKAGEDIR/DEBIAN  $PACKAGEDIR/usr/share/doc/mos-docker

        # Add initial copyright to package dir:
        echo -e "This package contains software under various licenses.\nSee the following files for details:\n" > $PACKAGEDIR/usr/share/doc/mos-docker/copyright

        # Add LICENSE from repo:
        cp "${{ github.workspace }}/LICENSE" "$PACKAGEDIR/usr/share/doc/mos-docker/LICENSE"
        echo -e "- LICENSE: License for packaging scripts" >> $PACKAGEDIR/usr/share/doc/mos-docker/copyright

        # Function to add licenses from repositories
        add_license_repo() {
          if [ -f "$(pwd)/NOTICE" ]; then
            cp "$(pwd)/NOTICE" "$PACKAGEDIR/usr/share/doc/mos-docker/NOTICE-$1"
          fi
          if [ -f "$(pwd)/LICENSE" ]; then
            cp "$(pwd)/LICENSE" "$PACKAGEDIR/usr/share/doc/mos-docker/LICENSE-$1"
            echo -e "- LICENSE-$1: License for $1 components" >> $PACKAGEDIR/usr/share/doc/mos-docker/copyright
          fi
        }

        # Function to add licenses from URL
        add_license_url() {
          if [ "$3" == "NOTICE" ] ; then
            wget -O $PACKAGEDIR/usr/share/doc/mos-docker/NOTICE-$1 "$2/NOTICE"
          fi
          wget -O $PACKAGEDIR/usr/share/doc/mos-docker/LICENSE-$1 "$2/LICENSE"
          echo -e "- LICENSE-$1: License for $1 components" >> $PACKAGEDIR/usr/share/doc/mos-docker/copyright
        }

        # dockerd
        cd $BUILDDIR
        git clone --branch $DOCKERD_V --single-branch --depth 1 https://github.com/moby/moby.git
        cd $BUILDDIR/moby
        export DOCKER_BUILDTAGS="exclude_graphdriver_devicemapper exclude_graphdriver_aufs nosystemd"
        ./hack/make.sh binary
        add_license_repo "Docker"

        cp $BUILDDIR/moby/bundles/binary-daemon/dockerd $PACKAGEDIR/usr/sbin/dockerd
        cp $BUILDDIR/moby/bundles/binary-daemon/docker-proxy $PACKAGEDIR/usr/sbin/docker-proxy

        # docker-cli
        cd $BUILDDIR
        export GOPATH=${{ github.workspace }}/go
        export DISABLE_WARN_OUTSIDE_CONTAINER=1
        git clone --branch $DOCKERD_V --single-branch --depth 1 https://github.com/docker/cli
        mkdir -p ${{ github.workspace }}/go/src/github.com/docker/cli
        cp -R $BUILDDIR/cli/* ${{ github.workspace }}/go/src/github.com/docker/cli
        cd $BUILDDIR/cli
        make binary -j20
        cp $BUILDDIR/cli/build/docker-linux-amd64 $PACKAGEDIR/usr/bin/docker
        add_license_repo "docker-cli"

        # containerd
        mkdir -p $BUILDDIR/containerd
        cd $BUILDDIR
        CONTAINERD_V=$(curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} -s https://api.github.com/repos/containerd/containerd/releases/latest | jq -r '.tag_name')
        wget -O $BUILDDIR/containerd/containerd.tar.gz https://github.com/containerd/containerd/releases/download/$CONTAINERD_V/containerd-static-${CONTAINERD_V#v}-linux-amd64.tar.gz
        tar -C $PACKAGEDIR/usr/ -xf $BUILDDIR/containerd/containerd.tar.gz
        add_license_url "containerd" "https://raw.githubusercontent.com/containerd/containerd/main" "NOTICE"

        # runc
        RUNC_V=$(curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} -s https://api.github.com/repos/opencontainers/runc/releases/latest | jq -r '.tag_name')
        wget -O $PACKAGEDIR/usr/sbin/runc https://github.com/opencontainers/runc/releases/download/$RUNC_V/runc.amd64
        add_license_url "runc" "https://raw.githubusercontent.com/opencontainers/runc/main" "NOTICE"

        # Add tini
        TINI_V=$(curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} -s https://api.github.com/repos/krallin/tini/releases/latest | jq -r '.tag_name')
        wget -O $PACKAGEDIR/usr/bin/tini-static https://github.com/krallin/tini/releases/download/$TINI_V/tini-static-amd64
        cd $PACKAGEDIR/usr/bin
        ln -sf /usr/bin/tini-static docker-init
        add_license_url "tini" "https://raw.githubusercontent.com/krallin/tini/master"

        # Add docker_buildx
        cd $BUILDDIR
        BUILDX_V=$(curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} -s https://api.github.com/repos/docker/buildx/releases/latest | jq -r '.tag_name')
        git clone --branch $BUILDX_V --single-branch --depth 1 https://github.com/docker/buildx.git
        cd buildx
        make build -j20
        cp $BUILDDIR/buildx/bin/build/docker-buildx $PACKAGEDIR/usr/lib/docker/cli-plugins/docker-buildx
        add_license_repo "buildx"

        # compose
        COMPOSE_V=$(curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} -s https://api.github.com/repos/docker/compose/releases/latest | jq -r '.tag_name')
        wget -O $PACKAGEDIR/usr/bin/docker-compose https://github.com/docker/compose/releases/download/$COMPOSE_V/docker-compose-linux-x86_64
        add_license_url "compose" "https://raw.githubusercontent.com/docker/compose/main" "NOTICE"

        # Copy MOS docker init.d script
        cp ${{ github.workspace }}/etc/init.d/docker $PACKAGEDIR/etc/init.d/docker

        # Add NOTICE line to copyright
        echo "- NOTICE-*: Additional notices where applicable" >> $PACKAGEDIR/usr/share/doc/mos-docker/copyright

        cat > $PACKAGEDIR/DEBIAN/control << EOF
        Package: Docker
        Version: ${DOCKERD_V#v}-mos
        Architecture: amd64
        Maintainer: admin@minenet.at
        Description: Custom Docker build for MOS
        EOF

        cd $BUILDDIR
        chmod -R 755 $PACKAGEDIR
        dpkg-deb --build docker_package mos-docker_${DOCKERD_V#v}_amd64.deb
        md5sum $BUILDDIR/mos-docker_${DOCKERD_V#v}_amd64.deb | awk '{print $1}' > $BUILDDIR/mos-docker_${DOCKERD_V#v}_amd64.deb.md5

        echo "DOCKERD_V=${DOCKERD_V#v}
        CONTAINERD_V=${CONTAINERD_V#v}
        RUNC_V=${RUNC_V#v}
        TINI_V=${TINI_V#v}
        BUILDX_V=${BUILDX_V#v}
        COMPOSE_V=${COMPOSE_V#v}
        BUILDDIR=$BUILDDIR" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.DOCKERD_V }}
        release_name: "Docker ${{ env.DOCKERD_V }}"
        body: |
          This is the custom Debian package from Docker for MOS

          ### Package contents:
          - [dockerd](https://github.com/moby/moby) v${{ env.DOCKERD_V }}
          - [docker-proxy](https://github.com/moby/moby) v${{ env.DOCKERD_V }}
          - [docker-cli](https://github.com/docker/cli) v${{ env.DOCKERD_V }}
          - [containerd](https://github.com/containerd/containerd) v${{ env.CONTAINERD_V }}
          - [runc](https://github.com/opencontainers/runc) v${{ env.RUNC_V }}
          - [tini](https://github.com/krallin/tini) v${{ env.TINI_V }}
          - [buildx](https://github.com/docker/buildx) v${{ env.BUILDX_V }}
          - [compose](https://github.com/docker/compose) v${{ env.COMPOSE_V }}
        draft: false
        prerelease: false

    - name: Upload deb to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.BUILDDIR }}/mos-docker_${{ env.DOCKERD_V }}_amd64.deb
        asset_name: mos-docker_${{ env.DOCKERD_V }}_amd64.deb
        asset_content_type: application/vnd.debian.binary-package

    - name: Upload md5 to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.BUILDDIR }}/mos-docker_${{ env.DOCKERD_V }}_amd64.deb.md5
        asset_name: mos-docker_${{ env.DOCKERD_V }}_amd64.deb.md5
        asset_content_type: text/plain


    - name: Cleanup
      if: always()
      run: rm -rf ${{ github.workspace }}/* ${{ github.workspace }}/.*
